# Overrides
COURSE = 
MAKE = /usr/bin/make
PLATFORM = 
VFLAG = 

.PHONY: compile-all
compile-all:
	$(MAKE) -C src compile-all CRSE=$(COURSE) PLATFORM=$(PLATFORM) VF=$(VFLAG)


.PHONY: build
build:
	$(MAKE) -C src build CRSE=$(COURSE) PLATFORM=$(PLATFORM) VF=$(VFLAG)

.PHONY: clean
clean:
	$(MAKE) -C src clean